HomeWork2
RedBear94/Java-Part-2 pull request #2
Opened 2020-02-25 11:12 UTC by RedBear94

2020-02-25 21:35 UTC, OKrylov requested changes
В целом все отлично, но есть пара мелких замечаний

2020-02-25 21:35 UTC, OKrylov commented on HomeWork2/src/com/company/Main.java
> +       int[][] numbers = new int[4][4];
для чего мы используем данный массив?

2020-02-25 21:35 UTC, OKrylov commented on HomeWork2/src/com/company/Main.java
> +       if (arrayFourOnFour[0].length != 4 || arrayFourOnFour.length != 4)
что если 2, 3 или 4 строка массива имеет длину != 4?

2020-02-25 21:57 UTC, RedBear94 commented on HomeWork2/src/com/company/Main.java
> +       int[][] numbers = new int[4][4];
Массив использовался для отладки, теперь удалён

2020-02-25 21:59 UTC, RedBear94 commented on HomeWork2/src/com/company/Main.java
> +       if (arrayFourOnFour[0].length != 4 || arrayFourOnFour.length != 4)
Внесены правки

2020-02-26 22:03 UTC, merged

2020-03-01 21:06 UTC, OKrylov reviewed
В целом по ДЗ все отлично, замечаний не имею