HomeWork3
RedBear94/Java-Part-2 pull request #3
Opened 2020-02-28 08:29 UTC by RedBear94

2020-03-03 07:10 UTC, OKrylov requested changes
В целом все отлично, но есть пара мелких замечаний

2020-03-03 07:10 UTC, OKrylov commented on HomeWork3/src/com/company/Main.java
> +        ArrayList<String> result = new ArrayList<>();
мы можем избавиться от этого списка, как и от вложенного ниже цикла, если будем просто использовать hashMap и её ключи для получения уникальных слов

2020-03-03 07:10 UTC, OKrylov commented on HomeWork3/src/com/company/Main.java
> +                if(str1 == str2){
строки сравниваем только на equals

2020-03-03 07:10 UTC, OKrylov commented on HomeWork3/src/com/company/Phonebook.java
> +    List<Human> phoneBook = new ArrayList<>();
стоит заменить на `Map<String, Human>` где ключ будет фамилия, тогда мы сможем оптимизировать метод get, исключив из него цикл

2020-03-03 11:46 UTC, RedBear94 commented on HomeWork3/src/com/company/Main.java
> +        ArrayList<String> result = new ArrayList<>();
Исправлено

2020-03-03 11:47 UTC, RedBear94 commented on HomeWork3/src/com/company/Main.java
> +                if(str1 == str2){
Теперь данная проверка отсутвует

2020-03-03 11:48 UTC, RedBear94 commented on HomeWork3/src/com/company/Phonebook.java
> +    List<Human> phoneBook = new ArrayList<>();
Исправлено

2020-03-08 23:07 UTC, OKrylov approved these changes
Идеальное ДЗ, замечаний нет

2020-03-09 12:36 UTC, merged